### ISSUE TITLE
how can we use mapnik (2.3) with a virtualenv for development?

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/static_map_generator#10]
Mapnik (2.3)  C++ en python bindings has to be installed on your machine before development.
How can we use python virtual environments when developing so mapnik and its python-bindings are available in the virtualenv?

**Comment by cahytinne** [comment]
* Installatie volgen op https://github.com/mapnik/mapnik/wiki/UbuntuInstallation **Install Mapnik from source** voor Mapnik 2.3.x
* Virtuele omgeving aanmaken  `mkvirtualenv static_map_generator`
* Links toevoegen in virtual env naar mapnik packages
```shell
ln -s /usr/lib/python2.7/dist-packages/mapnik ~/.virtualenvs/static_map_generator/lib/python2.7/site-packages/mapnik
ln -s /usr/lib/python2.7/dist-packages/mapnik2 ~/.virtualenvs/static_map_generator/lib/python2.7/site-packages/mapnik2
```
* Normale werkwijze verder zetten
```shell
(static_map_generator) pip install -r requirements-dev.txt
(static_map_generator) python setup.py develop
```

Op deze manier is Mapnik op de machine geïnstalleerd, maar wel uitvoerbaar in een virtuele python env waar ook andere packages geïnstalleerd staan
