### ISSUE TITLE
Tempfolders and tempfiles are not removed

### ISSUE THREAD

**Issue by cahytinne** [OnroerendErfgoed/static_map_generator#12]

**Comment by cedrikv** [comment]
additional info:
 - tempfolders are created in the /tmp folder 
 - tempfiles are removed when using generator as a service, after the image has been converted to a stream

**Comment by cahytinne** [comment]
> The cleaning of /tmp is done by the upstart script /etc/init/mounted-tmp.conf. The script is run by upstart everytime /tmp is mounted. Practically that means at every boot.
