### ISSUE TITLE
Add a ScaleRenderer

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/static_map_generator#5]
Implement a ScaleRenderer:
ScaleRenderer should calculate the scale (real world vs.map) and add a scalebar with Unit to the map.

(Use a scalebar and not the fraction notation so the created map-image can be used on websites (and you'll never know in which width and height they ware going to show the map-image.

**Comment by dieuska** [comment]
the current implementation of the scale renderer is not ready for production

**Comment by cahytinne** [comment]
In the latest version a simple number scale is added. Can be optimized in the next version.

**Comment by cahytinne** [comment]
Included in https://github.com/OnroerendErfgoed/static_map_generator/pull/21
